# Generated by Django 3.1.4 on 2020-12-03 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('waist', models.FloatField()),
                ('bp_judge', models.CharField(max_length=200)),
                ('pulse_count_judge', models.CharField(max_length=200)),
                ('bp_gluc', models.FloatField()),
                ('bt_chol', models.FloatField()),
                ('bt_trig', models.FloatField()),
                ('bt_hb', models.FloatField()),
                ('bt_crea', models.FloatField()),
                ('bt_sgot', models.FloatField()),
                ('bt_sgpt', models.FloatField()),
                ('bt_rgpt', models.FloatField()),
                ('bt_hbsa', models.CharField(max_length=200)),
                ('smoke_flag', models.CharField(max_length=200)),
                ('drinking_flag', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contents', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
